### PR TITLE
Fix font-weight regression

### LINKED ISSUE #965: Button text is no longer bold by default
**Describe the bug**
Text inside of `Button` no longer has `font-weight: 600` as a result of #941. The solution here is to restore the `font-weight` rule for `Button`, but using the correct `fontWeight` from `theme` instead of hardcoding it.

**Affected project(s) (e.g. `pcln-design-system`, `pcln-modal`, etc.)**
List of Design System projects relevant to this issue

**Expected behavior**
`Button` has `font-weight: 600`

**Screenshots**
Untitled

### PR DESCRIPTION
**Pull request by pcln-james**
Closes #965

### CODE REVIEW

File: packages/core/src/Button/Button.js [hunk 1]
```diff
@@ -94,6 +95,7 @@ export const buttonStyles = css`
   text-align: center;
   text-decoration: none;
   font-family: inherit;
+  font-weight: 600;
```
Comment (craigpalermo) [inline packages/core/src/Button/Button.js:98]: Is this where we wanted to get `fontWeight` from `theme`?

Comment (pcln-james) [reply packages/core/src/Button/Button.js:98]: bold is 700 though, what do you think?

**Review by craigpalermo — APPROVED** [review]

File: packages/core/src/Button/Button.js (hunk 1 above)
Comment (pcln-james) [reply packages/core/src/Button/Button.js:98]: We don't even bring in the 600 font weight, at least on the landing page so I don't think changing it to 700 is an issue because it is already using that when set to 600
image

Comment (sdalonzo) [reply packages/core/src/Button/Button.js:98]: yea i would change it to the theme.fontWeights that maps to 700

**Review by sdalonzo — APPROVED** [review]
