### PR TITLE
Fix package vulnerabilities in the next.js docsite

### LINKED ISSUE #825: Resolve security alerts in dependencies of Next.js docsite
https://github.com/priceline/design-system/network/alerts

### PR DESCRIPTION
**Pull request by sdalonzo**
Fixes #825 

cc @hakimelek

### CODE REVIEW

File: docs/src/NavLink.js [hunk 1]
```diff
@@ -37,16 +37,25 @@ export default withDocs(
...
-    >
-      <Base className={props.href === route.path ? 'active' : undefined}>
-        {props.children}
-      </Base>
-    </NextLink>
-  )
+  }) => {
+    if (isAbsoluteURL(href)) {
+      return (
+        <Base href={href} target='_blank'>
```
Comment (bmansell) [inline docs/src/NavLink.js:43]: Might want to throw a `rel='noopener'` on this.
